In [25]:
n=input("Enter values").split()
def three():
    for i in range(len(n)):
        n[i]=int(n[i])
        if(n[i]%3==0 or n[i]%5==0 or n[i]%7==0):
            print(n[i])
three()      

Enter values12 0 6
12
0
6


# Data science
### NumPy-Numerical Python 
### Pandas-Data Frames and Series
### MatPloltLib-Visualization
### Seaborn-makes difficult task easy
### IPython- Interactive python


In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [6]:
a_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(a_2d)
type(a)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [7]:
li=[1,3,4,5]
l_a=np.array(li)
print(l_a)

[1 3 4 5]


### ndim - returns the no of dimensions of the array
### shape -  returns the length of array
### size - returns size of array
### itemsize -  returns size of an element or item
### dtype - returns the type oa an array

In [10]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
n=np.random.randint(0,100,10)
print(n)
print(n.ndim)
print(n.size)
print(n.shape)
print(n.itemsize)
print(n.dtype)

[74 53 80 35 44 88 36  8 28 51]
1
10
(10,)
4
int32


In [3]:
n=np.random.randint(0,100,size=24).reshape(3,8)
print(n)
print(n.ndim)
print(n.size)
print(n.shape)
print(n.itemsize)
print(n.dtype)
print()
print(n[::-1])

[[ 7  8 91 42 57 43 14 44]
 [77 76 33 81 22 86 63 80]
 [48 96 35 62 26 87 42  5]]
2
24
(3, 8)
4
int32

[[48 96 35 62 26 87 42  5]
 [77 76 33 81 22 86 63 80]
 [ 7  8 91 42 57 43 14 44]]


In [4]:
n=np.ones(9)
print(n)
m=np.zeros(10)
print(m)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
k=np.linspace(0,2,10)
print(k)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [39]:
f=np.full((2,2,),7)#creates concstant element
print(f)

[[7 7]
 [7 7]]


In [42]:
e=np.eye(5)#identity array of given size
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
e1=np.empty((5,2))#in replace of 4 we can put any value then we get previously defined array values
print(e1)

[[3.56043053e-307 1.60219306e-306]
 [7.56571288e-307 1.89146896e-307]
 [1.37961302e-306 1.05699242e-307]
 [8.01097889e-307 1.42419530e-306]
 [8.34445138e-308 2.29179042e-312]]


In [7]:
c=np.array([[[2,4,5],[9,64,56]]])
print(c.ndim)
print(c)
c.reshape(1,6)

3
[[[ 2  4  5]
  [ 9 64 56]]]


array([[ 2,  4,  5,  9, 64, 56]])

In [8]:
c.ravel() #convert the multi-dimensional array into single-dimensional array

array([ 2,  4,  5,  9, 64, 56])

In [72]:
a=34
b=67
print(np.subtract(a,b))
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(100))
print(np.sin(b))
print(np.cos(b))
print(np.exp(64))
print(np.log(10))

-33
101
2278
0.5074626865671642
10.0
-0.8555199789753223
-0.5177697997895051
6.235149080811617e+27
2.302585092994046


In [9]:
a=np.arange(18).reshape(3,6)
print(a)
print("min",a.min())
print("max",a.max())
print("row wise max",a.max(axis=0))#axis=1 then row and axis=0 then column wise
print("column wise max",a.max(axis=1))
print("total sum",a.sum())
print("cumulative sum",a.cumsum())#cumulative sum
print("mean of a",np.mean(a))
print("median of a",np.median(a))
print(np.std(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
min 0
max 17
row wise max [12 13 14 15 16 17]
column wise max [ 5 11 17]
total sum 153
cumulative sum [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153]
mean of a 8.5
median of a 8.5
5.188127472091127


In [97]:
sa=np.array([23,23,11,1,3,7,656])
sa.sort()

In [99]:
print(sa)

[  1   3   7  11  23  23 656]


In [112]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
print(" \n",sa)
print("transpose\n",sa.transpose())
sa.T# used for transpose

 
 [[ 23  23  11]
 [  2   9   0]
 [  1   7 656]]
transpose
 [[ 23   2   1]
 [ 23   9   7]
 [ 11   0 656]]


array([[ 23,   2,   1],
       [ 23,   9,   7],
       [ 11,   0, 656]])

In [115]:
print(np.hsplit(sa,3))#horizontal split

[array([[23],
       [ 2],
       [ 1]]), array([[23],
       [ 9],
       [ 7]]), array([[ 11],
       [  0],
       [656]])]


In [123]:
print(np.vsplit(sa,3))#vertical split

[array([[23, 23, 11]]), array([[2, 9, 0]]), array([[  1,   7, 656]])]


In [124]:
a=np.array([1,2,3,34,5,6,7,9,8])
a

array([ 1,  2,  3, 34,  5,  6,  7,  9,  8])

In [127]:
np.hsplit(a,1)

[array([ 1,  2,  3, 34,  5,  6,  7,  9,  8])]

In [132]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
sa[0]

array([23, 23, 11])

In [133]:
sa[0:2]

array([[23, 23, 11],
       [ 2,  9,  0]])

In [134]:
sa[0:3]

array([[ 23,  23,  11],
       [  2,   9,   0],
       [  1,   7, 656]])

In [137]:
sa[0:2,0]# it returns the first element in specified rows

array([23,  2])

In [2]:
sa=np.array([[23,23,11],[2,9,0],[1,7,656]])
for i in range(np.ndim(sa)):
    for j in range(np.ndim(sa[i])):
        if(j==4):
            print(j)

In [11]:
sa[2,2]

656

In [3]:
a=np.random.randint(1,100,50)
print(a)
print("max:\t",a.max())
print("min:\t",a.min())
print("mean:\t",a.mean())
print("median:\t",np.max(a))
print("sd:\t",np.std(a))
print("sum:\t",a.sum())
print("cumulative sum:\t",a.cumsum())
print("sorting:\t",a.ravel())
print("hsplit:\t",np.hsplit(a,5))
print("transpose\n",a.T)

[ 4  8 95 44 12 60 47 68 39 90 77 54  6 57 23 67 81 30 45 94 65 89 45 76
 13 38 65 80 40 41 88 49 43 97 58 93  2 58 47 70 59 13 68 77 91  6 36  5
 55 93]
max:	 97
min:	 2
mean:	 53.22
median:	 97
sd:	 28.27174561289062
sum:	 2661
cumulative sum:	 [   4   12  107  151  163  223  270  338  377  467  544  598  604  661
  684  751  832  862  907 1001 1066 1155 1200 1276 1289 1327 1392 1472
 1512 1553 1641 1690 1733 1830 1888 1981 1983 2041 2088 2158 2217 2230
 2298 2375 2466 2472 2508 2513 2568 2661]
sorting:	 [ 4  8 95 44 12 60 47 68 39 90 77 54  6 57 23 67 81 30 45 94 65 89 45 76
 13 38 65 80 40 41 88 49 43 97 58 93  2 58 47 70 59 13 68 77 91  6 36  5
 55 93]
hsplit:	 [array([ 4,  8, 95, 44, 12, 60, 47, 68, 39, 90]), array([77, 54,  6, 57, 23, 67, 81, 30, 45, 94]), array([65, 89, 45, 76, 13, 38, 65, 80, 40, 41]), array([88, 49, 43, 97, 58, 93,  2, 58, 47, 70]), array([59, 13, 68, 77, 91,  6, 36,  5, 55, 93])]
transpose
 [ 4  8 95 44 12 60 47 68 39 90 77 54  6 57 23 67 81 30 45 94 65 89 4

In [7]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

In [2]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [8]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa